# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c3a40c18e2952e7b420a305c5b94c83d7b35911684159b3de90f323cf2e2c842a7b11112cbc9289d97f483235b837400425a656033a828da4e802fc91a8998d

test:
  secret_key_base: 487360ac9c185ba2fcb0c6bdc1446b2b3e9131e83bed90b6f57548be4568cbc8f04c1dd87af63a7e9b41c2032e9c3f7110e09354d6d6b185508adf7fc0f790b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
